<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>lbl_errorMessage</description>
   <name>lbl_errorMessage</name>
   <tag></tag>
   <elementGuidId>fc87c330-812d-44ce-a3ee-600e4c34f199</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='form-custom']/descendant::p[@class='error-input-message']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
